# Generated by Django 5.0.2 on 2024-02-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='car_photoes/%d/%m/%Y/', verbose_name='Фото')),
                ('year', models.IntegerField(null=True, verbose_name='Год выпуска')),
                ('transmission', models.TextField(null=True, verbose_name='Трансмиссия')),
                ('engine', models.IntegerField(null=True, verbose_name='Объём в литрах')),
                ('engine_type', models.TextField(null=True, verbose_name='Тип двигателя')),
                ('body_type_mileage', models.TextField(null=True, verbose_name='Тип кузова, Пробег автомобиля')),
                ('price_BYN', models.IntegerField(null=True, verbose_name='Цена в бел. рублях')),
                ('price_USD', models.IntegerField(null=True, verbose_name='Цена в бел. рублях')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='Город')),
                ('http_link', models.TextField(null=True, verbose_name='Ссылка')),
            ],
        ),
    ]
