"""
Django settings for tele_bot_project project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os  # это добавил
from dotenv import load_dotenv  # это добавил
from datetime import timedelta  # это добавил 16.03.024

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()  # это добавил
TOKEN = os.getenv('TOKEN')  # это добавил
TELEGRAM_ID = os.getenv('ADMIN_ID')  # это добавил


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5y@jh)*$$kybyhni=dk523_z$6xrazde0q7!b_ro)f(=#15*-4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # React 24.03.2024

# Application definition

########################################################## 16.03.2024
# CELERY
##REDIS_HOST = '127.0.0.1'
##REDIS_PORT = '6379'
##CELERY_BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'  # !!!!!
#CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
##CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'  # !!!!
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Europe/Moscow'  # !!!!
########################################################### 16.03.2024



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tele_bot_app.apps.TeleBotAppConfig',  # регистрация приложения из apps.py
    #'tele_bot_app.admin.admin_car', # ?????
    'rest_framework',  # добавление django rest framework, чтобы он заработал
    'drf_yasg',  # это добавили
    'django_filters',  # это добавили
    'admin_extra_buttons',  # это добавили 09.03.2024
    ##'django_celery_beat',  # это добавили 16.03.2024  Celery
    #'django_celery_results', # это добавили 16.03.2024  Celery
    'corsheaders',  #  24.03.2024 для react
]

################################################## 16.03.2024
# CELERY_BEAT_SCHEDULE
## CELERY_BEAT_SCHEDULE = {
##     'scheduled_message_task': {
##         'task': 'tele_bot_app.tasks.send_scheduled_message_task',
##         'schedule': timedelta(hours=9, minutes=20),  # Расписание отправки сообщения (каждый день в 9:00)
##     },
## }

# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_CACHE_BACKEND = 'django-cache'
#
# # celery setting.
# CELERY_CACHE_BACKEND = 'default'
#
# # django setting.
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#         'LOCATION': 'my_cache_table',
#     }
# }


########################################################### 16.03.2024


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  #  24.03.2024 для react
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tele_bot_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # [os.path.join(BASE_DIR, 'templates')]
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tele_bot_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# добавил postgres
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',  # БД PostgreSQL
        'NAME': 'av_by_data_bases',
        'USER': 'av_by_admin',
        'PASSWORD': 'AVLioneLMessI1024BY',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',  # это пагинация общая
    'PAGE_SIZE': 5,  # это пагинация общая
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',  # Это добавили
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],  # Это добавили
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'  #  24.03.2024 для react AllowAny может быть заменено, так как это для любого пользователя
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
           'rest_framework.authentication.TokenAuthentication',  # 16.04.2024 аунтификация пользователей
       ],
}

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
]

